### ISSUE TITLE
Details Panel

### ISSUE THREAD

**Issue by tfgordon** [policycompass/argument-editor#3]
Add a  "Details" panel showing the meta data of the selected node (statement, argument, issue) and providing a way for the user to edit this data.

This metadata can be arbitrary YAML, so we need to discuss the design of the user interface.

**Comment by tfgordon** [comment]
The text shown in statement nodes could also be edited in this panel.

**Comment by th0br0** [comment]
This is a UI-specific bug. WellAgEd does not aim to provide a UI, only the building blocks & graph window itself. So please report against PC or PC-frontend.
